### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by nilsw-ra** [okfn/reconcile-csv#43]
When I choose the **CSV Reconciliation Service** for reconciling a column I get an error message 

Guess Types query failed error : java.io.IOException: HTTP error 500 : Server Error for URL /reconcile

and the reconcile-csv console log shows this exception:

`2022-09-27 14:45:15.777:WARN:oejs.AbstractHttpConnection:/reconcile
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at clojure.core$deref_future.invoke(core.clj:2108)
        at clojure.core$future_call$reify__6267.deref(core.clj:6308)
        at clojure.core$deref.invoke(core.clj:2128)
        at clojure.core$map$fn__4207.invoke(core.clj:2487)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:67)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$zipmap.invoke(core.clj:2713)
        at reconcile_csv.core$reconcile_params.invoke(core.clj:130)
        at reconcile_csv.core$reconcile.invoke(core.clj:140)
        at reconcile_csv.core$fn__2664.invoke(core.clj:225)
        at compojure.core$make_route$fn__534.invoke(core.clj:94)
        at compojure.core$if_route$fn__522.invoke(core.clj:40)
        at compojure.core$if_method$fn__515.invoke(core.clj:25)
        at compojure.core$routing$fn__540.invoke(core.clj:107)
        at clojure.core$some.invoke(core.clj:2443)
        at compojure.core$routing.doInvoke(core.clj:107)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:619)
        at compojure.core$routes$fn__544.invoke(core.clj:112)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__1341.invoke(keyword_params.clj:32)
        at ring.middleware.nested_params$wrap_nested_params$fn__1383.invoke(nested_params.clj:70)
        at ring.middleware.params$wrap_params$fn__205.invoke(params.clj:58)
        at ring.adapter.jetty$proxy_handler$fn__81.invoke(jetty.clj:18)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$0.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:363)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by:
java.lang.NullPointerException`

I suspect I am doing something wrong, but what?

**Comment by tfmorris** [comment]
You might want to look at #5 and #6 to see if they're relevant to your situation. There should be more to your stack trace after the "Caused by:" which would include the information to be able to tell whether or not it's the same problem.
