### ISSUE TITLE
Can't run reconcile-csv.jar file

### ISSUE THREAD

**Issue by santanu4** [okfn/reconcile-csv#9]
I am a newbie i data reconciliation with open refine and I am still in learner stage. I am using windows XP SP3 and I have java run time environemnt installed in my machine. My question is where do I run the command:-
java -jar reconcile-csv-1.0.1-SNAPSHOT-standalone.jar <file> <primary search column> <column with id's>

I have tried running it in windows command prompt and I used different prmutationsa dn combinations to see if any runs. I have also tried double clicking and running the reconcile-csv.jar file. It threw a hava virtual machine error and eventually didn't proceed. I want to know how to make it run?

**Comment by sjg-transparency** [comment]
I'm very much in the same position as the original poster - I have very little experience of doing anything in command prompt so I'm probably doing something very obviously wrong, but I have absolutely no clue what.

I've download the file and stored it in FolderX. The Data I want to use as my reconciliation file i.e. the one with the IDs is in Folder Y. I've tried putting the below into the command prompt but it keeps on saying "Unable to access jarfile P:\FolderX\reconcile-csv-0.1.2.jar

java -jar "P:\FolderX\reconcile-csv-0.1.2.jar" P\FolderY\HouseOfLords-Donations-Reconciliation.csv "Name" "PersonID"

Am I missing something or is my computer being buggy? If I can get this going ASAP it'll save me a load of time with what I'm trying to do, so any swift assistance on this would be greatly appreciated.

**Comment by mihi-tr** [comment]
Interesting issue, toe command line seems ok - if your path is correct. Can you dir P:\FolderX\reconcile-csv-0.1.2.jar . Also I do think the double quotes should not be needed...

**Comment by sjg-transparency** [comment]
Think I'm getting somewhere. It now seems to be having problems finding the file I want to reconcile from. You might have to spell things out very simply for me if I'm doing something wrong because I have no idea how this language works.

Thanks for your assistance

C:\Users\Steve>java -jar "P:_Shared files exc DSP\PROJECTS\Lobbying\Data\reconc
ile-csv-0.1.2.jar" "P:_Shared files exc DSP\PROJECTS\Lobbying\Data\HouseOfLords
-Donations-Reconciliation.csv" Name PersonID
Exception in thread "main" java.io.FileNotFoundException: P:_Shared files exc D
SP\PROJECTS\Lobbying\Data\HouseOfLords-Donations-Reconciliation.csv (The system
cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at clojure.java.io$fn__8638.invoke(io.clj:233)
        at clojure.java.io$fn__8577$G__8542__8584.invoke(io.clj:73)
        at clojure.java.io$fn__8650.invoke(io.clj:262)
        at clojure.java.io$fn__8577$G__8542__8584.invoke(io.clj:73)
        at clojure.java.io$fn__8612.invoke(io.clj:169)
        at clojure.java.io$fn__8551$G__8546__8558.invoke(io.clj:73)
        at clojure.java.io$reader.doInvoke(io.clj:106)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:161)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:619)
        at clojure.core$slurp.doInvoke(core.clj:6278)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at reconcile_csv.core$_main$fn__2676.invoke(core.clj:238)
        at clojure.lang.Atom.swap(Atom.java:51)
        at clojure.core$swap_BANG_.invoke(core.clj:2161)
        at reconcile_csv.core$_main.invoke(core.clj:238)
        at clojure.lang.AFn.applyToHelper(AFn.java:167)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at reconcile_csv.core.main(Unknown Source)

**Comment by mihi-tr** [comment]
I could be your folder names with a ton of spaces in them - not sure it handles those well. Could you move your files to the same folder? Or type cd "THEFOLDERWITHYOURFILE" and just run:
java -jar "P:_Shared files exc DSP\PROJECTS\Lobbying\Data\reconc
ile-csv-0.1.2.jar" thefile.csv name personID

**Comment by sjg-transparency** [comment]
Morning Michael,

Sorry for the very late reply. In the end I had to do this the long hard way, but I’ll try your solution the next time I need to reconcile some data.

Thanks for your time
Steve

**Comment by tfmorris** [comment]
@sjg-transparency https://discuss.okfn.org/t/remembering-michael-bauer/1166

**Comment by abubelinha** [comment]
I had similar issues and finally it was a problem of a malformed csv.
Solution: I loaded myt text file with Openrefine, and used the "export as csv", as described here:
https://groups.google.com/forum/#!msg/openrefine/jgzicV-Bj9g/HhHu37x1AwAJ

After that, I could use it as a openrefine reconciliation service with reconcile-csv like this:

C:\currentpath> java -Xmx1g -jar C:\path-to-executable\reconcile-csv-0.1.2.jar C:\path-to-csv\myfile.csv "name" "id"
